from tkinter import *

root = Tk()
root.title('Harvest Message Generator')
root.geometry("470x400")

AugLabel = Label(root, text="Augment")
RemLabel = Label(root, text="Remove")
RemAddLabel = Label(root, text="Remove/Add")

AugLabel.grid(row=0, column=0, columnspan=3)
RemLabel.grid(row=0, column=3, columnspan=3)
RemAddLabel.grid(row=0, column=6, columnspan=3)

# Augment

AugAmountLabel = Label(root, text="#")
AugPriceLabel = Label(root, text="$")

AugAmountLabel.grid(row=1, column=1)
AugPriceLabel.grid(row=1, column=2)

AugSpeedCheck = Checkbutton(root, text="Speed", justify=LEFT)
AugLifeCheck = Checkbutton(root, text="Life", justify=LEFT)
AugFireCheck = Checkbutton(root, text="Fire", justify=LEFT)
AugColdCheck = Checkbutton(root, text="Cold", justify=LEFT)
AugLightCheck = Checkbutton(root, text="Lightning", justify=LEFT)
AugChaosCheck = Checkbutton(root, text="Chaos", justify=LEFT)
AugPhysCheck = Checkbutton(root, text="Physical", justify=LEFT)
AugAttCheck = Checkbutton(root, text="Attack", justify=LEFT)
AugCastCheck = Checkbutton(root, text="Caster", justify=LEFT)

AugSpeedCheck.grid(row=2, column=0, padx=3, sticky=W)
AugLifeCheck.grid(row=3, column=0, padx=3, sticky=W)
AugFireCheck.grid(row=4, column=0, padx=3, sticky=W)
AugColdCheck.grid(row=5, column=0, padx=3, sticky=W)
AugLightCheck.grid(row=6, column=0, padx=3, sticky=W)
AugChaosCheck.grid(row=7, column=0, padx=3, sticky=W)
AugPhysCheck.grid(row=8, column=0, padx=3, sticky=W)
AugAttCheck.grid(row=9, column=0, padx=3, sticky=W)
AugCastCheck.grid(row=10, column=0, padx=3, sticky=W)

AugSpeedAmountEntry = Entry(root, width=3)
AugLifeAmountEntry = Entry(root, width=3)
AugFireAmountEntry = Entry(root, width=3)
AugColdAmountEntry = Entry(root, width=3)
AugLightAmountEntry = Entry(root, width=3)
AugChaosAmountEntry = Entry(root, width=3)
AugPhysAmountEntry = Entry(root, width=3)
AugAttAmountEntry = Entry(root, width=3)
AugCastAmountEntry = Entry(root, width=3)

AugSpeedAmountEntry.grid(row=2, column=1, padx=3)
AugLifeAmountEntry.grid(row=3, column=1)
AugFireAmountEntry.grid(row=4, column=1)
AugColdAmountEntry.grid(row=5, column=1)
AugLightAmountEntry.grid(row=6, column=1)
AugChaosAmountEntry.grid(row=7, column=1)
AugPhysAmountEntry.grid(row=8, column=1)
AugAttAmountEntry.grid(row=9, column=1)
AugCastAmountEntry.grid(row=10, column=1)

AugSpeedPriceEntry = Entry(root, width=5)
AugLifePriceEntry = Entry(root, width=5)
AugFirePriceEntry = Entry(root, width=5)
AugColdPriceEntry = Entry(root, width=5)
AugLightPriceEntry = Entry(root, width=5)
AugChaosPriceEntry = Entry(root, width=5)
AugPhysPriceEntry = Entry(root, width=5)
AugAttPriceEntry = Entry(root, width=5)
AugCastPriceEntry = Entry(root, width=5)

AugSpeedPriceEntry.grid(row=2, column=2, padx=3)
AugLifePriceEntry.grid(row=3, column=2)
AugFirePriceEntry.grid(row=4, column=2)
AugColdPriceEntry.grid(row=5, column=2)
AugLightPriceEntry.grid(row=6, column=2)
AugChaosPriceEntry.grid(row=7, column=2)
AugPhysPriceEntry.grid(row=8, column=2)
AugAttPriceEntry.grid(row=9, column=2)
AugCastPriceEntry.grid(row=10, column=2)

AugGenerateButton = Button(root, text="Generate")
AugGenerateButton.grid(row=11, column=0, columnspan=3)

# Remove

RemAmountLabel = Label(root, text="#")
RemPriceLabel = Label(root, text="$")

RemAmountLabel.grid(row=1, column=4)
RemPriceLabel.grid(row=1, column=5)

RemSpeedCheck = Checkbutton(root, text="Speed", justify=LEFT)
RemLifeCheck = Checkbutton(root, text="Life", justify=LEFT)
RemFireCheck = Checkbutton(root, text="Fire", justify=LEFT)
RemColdCheck = Checkbutton(root, text="Cold", justify=LEFT)
RemLightCheck = Checkbutton(root, text="Lightning", justify=LEFT)
RemChaosCheck = Checkbutton(root, text="Chaos", justify=LEFT)
RemPhysCheck = Checkbutton(root, text="Physical", justify=LEFT)
RemAttCheck = Checkbutton(root, text="Attack", justify=LEFT)
RemCastCheck = Checkbutton(root, text="Caster", justify=LEFT)

RemSpeedCheck.grid(row=2, column=3, padx=3, sticky=W)
RemLifeCheck.grid(row=3, column=3, padx=3, sticky=W)
RemFireCheck.grid(row=4, column=3, padx=3, sticky=W)
RemColdCheck.grid(row=5, column=3, padx=3, sticky=W)
RemLightCheck.grid(row=6, column=3, padx=3, sticky=W)
RemChaosCheck.grid(row=7, column=3, padx=3, sticky=W)
RemPhysCheck.grid(row=8, column=3, padx=3, sticky=W)
RemAttCheck.grid(row=9, column=3, padx=3, sticky=W)
RemCastCheck.grid(row=10, column=3, padx=3, sticky=W)

RemSpeedAmountEntry = Entry(root, width=3)
RemLifeAmountEntry = Entry(root, width=3)
RemFireAmountEntry = Entry(root, width=3)
RemColdAmountEntry = Entry(root, width=3)
RemLightAmountEntry = Entry(root, width=3)
RemChaosAmountEntry = Entry(root, width=3)
RemPhysAmountEntry = Entry(root, width=3)
RemAttAmountEntry = Entry(root, width=3)
RemCastAmountEntry = Entry(root, width=3)

RemSpeedAmountEntry.grid(row=2, column=4, padx=3)
RemLifeAmountEntry.grid(row=3, column=4)
RemFireAmountEntry.grid(row=4, column=4)
RemColdAmountEntry.grid(row=5, column=4)
RemLightAmountEntry.grid(row=6, column=4)
RemChaosAmountEntry.grid(row=7, column=4)
RemPhysAmountEntry.grid(row=8, column=4)
RemAttAmountEntry.grid(row=9, column=4)
RemCastAmountEntry.grid(row=10, column=4)

RemSpeedPriceEntry = Entry(root, width=5)
RemLifePriceEntry = Entry(root, width=5)
RemFirePriceEntry = Entry(root, width=5)
RemColdPriceEntry = Entry(root, width=5)
RemLightPriceEntry = Entry(root, width=5)
RemChaosPriceEntry = Entry(root, width=5)
RemPhysPriceEntry = Entry(root, width=5)
RemAttPriceEntry = Entry(root, width=5)
RemCastPriceEntry = Entry(root, width=5)

RemSpeedPriceEntry.grid(row=2, column=5, padx=3)
RemLifePriceEntry.grid(row=3, column=5)
RemFirePriceEntry.grid(row=4, column=5)
RemColdPriceEntry.grid(row=5, column=5)
RemLightPriceEntry.grid(row=6, column=5)
RemChaosPriceEntry.grid(row=7, column=5)
RemPhysPriceEntry.grid(row=8, column=5)
RemAttPriceEntry.grid(row=9, column=5)
RemCastPriceEntry.grid(row=10, column=5)

RemGenerateButton = Button(root, text="Generate")
RemGenerateButton.grid(row=11, column=3, columnspan=3)

# Remove/Add

RemAddAmountLabel = Label(root, text="#")
RemAddPriceLabel = Label(root, text="$")

RemAddAmountLabel.grid(row=1, column=7)
RemAddPriceLabel.grid(row=1, column=8)

RemAddSpeedCheck = Checkbutton(root, text="Speed", justify=LEFT)
RemAddLifeCheck = Checkbutton(root, text="Life", justify=LEFT)
RemAddFireCheck = Checkbutton(root, text="Fire", justify=LEFT)
RemAddColdCheck = Checkbutton(root, text="Cold", justify=LEFT)
RemAddLightCheck = Checkbutton(root, text="Lightning", justify=LEFT)
RemAddChaosCheck = Checkbutton(root, text="Chaos", justify=LEFT)
RemAddPhysCheck = Checkbutton(root, text="Physical", justify=LEFT)
RemAddAttCheck = Checkbutton(root, text="Attack", justify=LEFT)
RemAddCastCheck = Checkbutton(root, text="Caster", justify=LEFT)

RemAddSpeedCheck.grid(row=2, column=6, padx=3, sticky=W)
RemAddLifeCheck.grid(row=3, column=6, padx=3, sticky=W)
RemAddFireCheck.grid(row=4, column=6, padx=3, sticky=W)
RemAddColdCheck.grid(row=5, column=6, padx=3, sticky=W)
RemAddLightCheck.grid(row=6, column=6, padx=3, sticky=W)
RemAddChaosCheck.grid(row=7, column=6, padx=3, sticky=W)
RemAddPhysCheck.grid(row=8, column=6, padx=3, sticky=W)
RemAddAttCheck.grid(row=9, column=6, padx=3, sticky=W)
RemAddCastCheck.grid(row=10, column=6, padx=3, sticky=W)

RemAddSpeedAmountEntry = Entry(root, width=3)
RemAddLifeAmountEntry = Entry(root, width=3)
RemAddFireAmountEntry = Entry(root, width=3)
RemAddColdAmountEntry = Entry(root, width=3)
RemAddLightAmountEntry = Entry(root, width=3)
RemAddChaosAmountEntry = Entry(root, width=3)
RemAddPhysAmountEntry = Entry(root, width=3)
RemAddAttAmountEntry = Entry(root, width=3)
RemAddCastAmountEntry = Entry(root, width=3)

RemAddSpeedAmountEntry.grid(row=2, column=7, padx=3)
RemAddLifeAmountEntry.grid(row=3, column=7)
RemAddFireAmountEntry.grid(row=4, column=7)
RemAddColdAmountEntry.grid(row=5, column=7)
RemAddLightAmountEntry.grid(row=6, column=7)
RemAddChaosAmountEntry.grid(row=7, column=7)
RemAddPhysAmountEntry.grid(row=8, column=7)
RemAddAttAmountEntry.grid(row=9, column=7)
RemAddCastAmountEntry.grid(row=10, column=7)

RemAddSpeedPriceEntry = Entry(root, width=5)
RemAddLifePriceEntry = Entry(root, width=5)
RemAddFirePriceEntry = Entry(root, width=5)
RemAddColdPriceEntry = Entry(root, width=5)
RemAddLightPriceEntry = Entry(root, width=5)
RemAddChaosPriceEntry = Entry(root, width=5)
RemAddPhysPriceEntry = Entry(root, width=5)
RemAddAttPriceEntry = Entry(root, width=5)
RemAddCastPriceEntry = Entry(root, width=5)

RemAddSpeedPriceEntry.grid(row=2, column=8, padx=3)
RemAddLifePriceEntry.grid(row=3, column=8)
RemAddFirePriceEntry.grid(row=4, column=8)
RemAddColdPriceEntry.grid(row=5, column=8)
RemAddLightPriceEntry.grid(row=6, column=8)
RemAddChaosPriceEntry.grid(row=7, column=8)
RemAddPhysPriceEntry.grid(row=8, column=8)
RemAddAttPriceEntry.grid(row=9, column=8)
RemAddCastPriceEntry.grid(row=10, column=8)

RemAddGenerateButton = Button(root, text="Generate")
RemAddGenerateButton.grid(row=11, column=6, columnspan=3)

root.mainloop()
